[package]
name = "hashmap_benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nohash-hasher = "0.2"
indexmap = "2.0"
crossbeam = "0.8"
rand = "0.8.5"
seahash = "4.1.0"
